"""adição da cofiguração geral do casamento

Revision ID: 3d9244f793fd
Revises: e5f0135a437e
Create Date: 2025-06-06 09:55:52.569309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d9244f793fd'
down_revision: Union[str, None] = 'e5f0135a437e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cor_principal', sa.String(), nullable=True),
    sa.Column('cor_secundaria', sa.String(), nullable=True),
    sa.Column('chave_pix', sa.String(), nullable=True),
    sa.Column('data_casamento', sa.String(), nullable=True),
    sa.Column('hora_casamento', sa.String(), nullable=True),
    sa.Column('local_casamento', sa.String(), nullable=True),
    sa.Column('cidade_casamento', sa.String(), nullable=True),
    sa.Column('estado_casamento', sa.String(), nullable=True),
    sa.Column('pais_casamento', sa.String(), nullable=True),
    sa.Column('nome_noivo_1', sa.String(), nullable=True),
    sa.Column('nome_noivo_2', sa.String(), nullable=True),
    sa.Column('template_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_configurations_id'), 'configurations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_configurations_id'), table_name='configurations')
    op.drop_table('configurations')
    # ### end Alembic commands ###
