"""mudança no modelo de produto da loja de presente para que ele receba linkes de imagems (futuremente poderemos ainda modificar para receber um modelo photo)

Revision ID: 7d0f2a2fcdff
Revises: e5165199c840
Create Date: 2025-06-04 09:40:21.563552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d0f2a2fcdff'
down_revision: Union[str, None] = 'e5165199c840'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gift_products', 'image',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gift_products', 'image',
               existing_type=sa.String(),
               type_=postgresql.BYTEA(),
               existing_nullable=False)
    # ### end Alembic commands ###
