"""atualização das configurações e atualizações de tradução

Revision ID: b47bb1574707
Revises: d4bb1d0f5aa4
Create Date: 2025-06-06 15:27:01.135415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b47bb1574707'
down_revision: Union[str, None] = 'd4bb1d0f5aa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gift_shop_purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['gift_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gift_shop_purchases_id'), 'gift_shop_purchases', ['id'], unique=False)
    op.drop_index('ix_gift_shop_buy_products_id', table_name='gift_shop_buy_products')
    op.drop_table('gift_shop_buy_products')
    op.add_column('configurations', sa.Column('primary_color', sa.String(), nullable=True))
    op.add_column('configurations', sa.Column('secondary_color', sa.String(), nullable=True))
    op.add_column('configurations', sa.Column('pix_key', sa.String(), nullable=True))
    op.add_column('configurations', sa.Column('pix_city', sa.String(), nullable=True))
    op.add_column('configurations', sa.Column('wedding_date', sa.String(), nullable=True))
    op.add_column('configurations', sa.Column('wedding_time', sa.String(), nullable=True))
    op.add_column('configurations', sa.Column('wedding_location', sa.String(), nullable=True))
    op.add_column('configurations', sa.Column('wedding_city', sa.String(), nullable=True))
    op.add_column('configurations', sa.Column('wedding_state', sa.String(), nullable=True))
    op.add_column('configurations', sa.Column('wedding_country', sa.String(), nullable=True))
    op.add_column('configurations', sa.Column('spouse_name_1', sa.String(), nullable=True))
    op.add_column('configurations', sa.Column('spouse_name_2', sa.String(), nullable=True))
    op.drop_column('configurations', 'local_casamento')
    op.drop_column('configurations', 'hora_casamento')
    op.drop_column('configurations', 'pais_casamento')
    op.drop_column('configurations', 'cor_secundaria')
    op.drop_column('configurations', 'cidade_casamento')
    op.drop_column('configurations', 'nome_noivo_2')
    op.drop_column('configurations', 'cor_principal')
    op.drop_column('configurations', 'chave_pix')
    op.drop_column('configurations', 'nome_noivo_1')
    op.drop_column('configurations', 'data_casamento')
    op.drop_column('configurations', 'estado_casamento')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configurations', sa.Column('estado_casamento', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('configurations', sa.Column('data_casamento', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('configurations', sa.Column('nome_noivo_1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('configurations', sa.Column('chave_pix', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('configurations', sa.Column('cor_principal', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('configurations', sa.Column('nome_noivo_2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('configurations', sa.Column('cidade_casamento', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('configurations', sa.Column('cor_secundaria', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('configurations', sa.Column('pais_casamento', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('configurations', sa.Column('hora_casamento', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('configurations', sa.Column('local_casamento', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('configurations', 'spouse_name_2')
    op.drop_column('configurations', 'spouse_name_1')
    op.drop_column('configurations', 'wedding_country')
    op.drop_column('configurations', 'wedding_state')
    op.drop_column('configurations', 'wedding_city')
    op.drop_column('configurations', 'wedding_location')
    op.drop_column('configurations', 'wedding_time')
    op.drop_column('configurations', 'wedding_date')
    op.drop_column('configurations', 'pix_city')
    op.drop_column('configurations', 'pix_key')
    op.drop_column('configurations', 'secondary_color')
    op.drop_column('configurations', 'primary_color')
    op.create_table('gift_shop_buy_products',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('payed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('payed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('guest_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], name='gift_shop_buy_products_guest_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['gift_products.id'], name='gift_shop_buy_products_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='gift_shop_buy_products_pkey')
    )
    op.create_index('ix_gift_shop_buy_products_id', 'gift_shop_buy_products', ['id'], unique=False)
    op.drop_index(op.f('ix_gift_shop_purchases_id'), table_name='gift_shop_purchases')
    op.drop_table('gift_shop_purchases')
    # ### end Alembic commands ###
