"""melria no photo_challenge

Revision ID: cf336fa448eb
Revises: c190a95dc693
Create Date: 2025-06-02 15:18:07.590703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf336fa448eb'
down_revision: Union[str, None] = 'c190a95dc693'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'photo_challenges', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'photo_challenges', type_='unique')
    # ### end Alembic commands ###
