"""atualisação da loja de presentes

Revision ID: d4bb1d0f5aa4
Revises: e3a5299d8f02
Create Date: 2025-06-06 14:46:43.926907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4bb1d0f5aa4'
down_revision: Union[str, None] = 'e3a5299d8f02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gift_products', sa.Column('photo_id', sa.Integer(), nullable=True))
    op.alter_column('gift_products', 'image',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'gift_products', 'photos', ['photo_id'], ['id'])
    op.drop_column('gift_shops', 'pix_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gift_shops', sa.Column('pix_key', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'gift_products', type_='foreignkey')
    op.alter_column('gift_products', 'image',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('gift_products', 'photo_id')
    # ### end Alembic commands ###
