"""atualização do convite

Revision ID: d77526ef648f
Revises: 3d9244f793fd
Create Date: 2025-06-06 11:14:37.927832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd77526ef648f'
down_revision: Union[str, None] = '3d9244f793fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('photo_album_id', sa.Integer(), nullable=True))
    op.add_column('invitations', sa.Column('cover_photo_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'invitations', 'photos', ['cover_photo_id'], ['id'])
    op.create_foreign_key(None, 'invitations', 'photo_albums', ['photo_album_id'], ['id'])
    op.drop_column('invitations', 'photo_album_url')
    op.drop_column('invitations', 'background_color')
    op.drop_column('invitations', 'background_image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('background_image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('invitations', sa.Column('background_color', sa.VARCHAR(length=7), autoincrement=False, nullable=True))
    op.add_column('invitations', sa.Column('photo_album_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'invitations', type_='foreignkey')
    op.drop_constraint(None, 'invitations', type_='foreignkey')
    op.drop_column('invitations', 'cover_photo_id')
    op.drop_column('invitations', 'photo_album_id')
    # ### end Alembic commands ###
