"""atualização do timeline agora com fotos internas

Revision ID: e3a5299d8f02
Revises: d77526ef648f
Create Date: 2025-06-06 12:06:07.549300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3a5299d8f02'
down_revision: Union[str, None] = 'd77526ef648f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timeline_items', sa.Column('photo_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'timeline_items', 'photos', ['photo_id'], ['id'])
    op.drop_column('timeline_items', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timeline_items', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'timeline_items', type_='foreignkey')
    op.drop_column('timeline_items', 'photo_id')
    # ### end Alembic commands ###
