"""atualização das fotos

Revision ID: e5f0135a437e
Revises: eea827db8db6
Create Date: 2025-06-05 16:08:41.669191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5f0135a437e'
down_revision: Union[str, None] = 'eea827db8db6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo_albums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_albums_id'), 'photo_albums', ['id'], unique=False)
    op.alter_column('gift_shop_buy_products', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('photos', sa.Column('photo_album_id', sa.Integer(), nullable=True))
    op.drop_constraint('photos_hash_id_key', 'photos', type_='unique')
    op.drop_constraint('photos_guest_id_fkey', 'photos', type_='foreignkey')
    op.create_foreign_key(None, 'photos', 'photo_albums', ['photo_album_id'], ['id'])
    op.drop_column('photos', 'hash_id')
    op.drop_column('photos', 'guest_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('guest_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('photos', sa.Column('hash_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'photos', type_='foreignkey')
    op.create_foreign_key('photos_guest_id_fkey', 'photos', 'guests', ['guest_id'], ['id'])
    op.create_unique_constraint('photos_hash_id_key', 'photos', ['hash_id'])
    op.drop_column('photos', 'photo_album_id')
    op.alter_column('gift_shop_buy_products', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_photo_albums_id'), table_name='photo_albums')
    op.drop_table('photo_albums')
    # ### end Alembic commands ###
