"""adição do buy products

Revision ID: eea827db8db6
Revises: 7d0f2a2fcdff
Create Date: 2025-06-04 17:06:46.980068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eea827db8db6'
down_revision: Union[str, None] = '7d0f2a2fcdff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gift_shop_buy_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('payed', sa.Boolean(), nullable=True),
    sa.Column('payed_at', sa.DateTime(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['gift_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gift_shop_buy_products_id'), 'gift_shop_buy_products', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gift_shop_buy_products_id'), table_name='gift_shop_buy_products')
    op.drop_table('gift_shop_buy_products')
    # ### end Alembic commands ###
