services:
  postgres:
    image: postgres:15-alpine
    container_name: weddingplanner_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: ./backend/fastapi
      dockerfile: Dockerfile
    container_name: weddingplanner_api
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend/fastapi:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

  waha:
    image: devlikeapro/waha
    container_name: weddingplanner_whatsapp
    ports:
      - "3000:3000"
    environment:
      - WHATSAPP_RESTART_ALL_SESSIONS=true
    volumes:
      - waha_data:/app/store

  # frontend:
  #   build: 
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: weddingplanner_frontend
  #   ports:
  #     - "3000:3000"

volumes:
  postgres_data:
  waha_data: 